name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Lint Docker Compose
        run: docker-compose -f compose.yaml config
        
      - name: Run Tests
        run: |
          docker-compose -f compose.yaml up -d
          curl http://localhost:3000/
          docker-compose -f compose.yaml down
      
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./compose.yaml
          push: true
          tags: diarama13/crud-fullstack-cicd:latest

      # - name: Deploy to Server
      #   run: |
      #     echo "Deploying to server..."
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
      #     docker-compose -f /path/to/compose.yaml pull
      #     docker-compose -f /path/to/compose.yaml up -d
      #     EOF
